created frontend setup
jwp-consulting/projectify-frontend pull request #4
Opened 2021-12-08 06:07 UTC by Mygithub-me

2021-12-08 06:23 UTC, justuswilhelm commented
Please commit package.json.lock
Please change the commit message to "Create new project"

2021-12-08 06:23 UTC, justuswilhelm requested changes
Please see the comments for change requests

2021-12-08 06:23 UTC, justuswilhelm commented on .gitignore
> +package-lock.json
This file shouldn't be ignored and be checked in instead. Also, this file has a missing newline at the end

2021-12-08 06:23 UTC, justuswilhelm commented on src/components/Welcome.tsx
> +}
Missing newline

2021-12-08 06:23 UTC, justuswilhelm commented on src/logo.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 841.9 595.3"><g fill="#61DAFB"><path d="M666.3 296.5c0-32.5-40.7-63.3-103.1-82.4 14.4-63.6 8-114.2-20.2-130.4-6.5-3.8-14.1-5.6-22.4-5.6v22.3c4.6 0
Could you remove the logo?

2021-12-08 06:23 UTC, justuswilhelm commented on src/redux/Store.js
> +export default store;
Missing newline

2021-12-08 06:23 UTC, justuswilhelm commented on src/redux/reducers/RootReducer.js
> +})
Missing newline

2021-12-08 06:23 UTC, justuswilhelm commented on package.json
> +  "name": "simpletodo-frontend",
This should say 
```suggestion
  "name": "projectify-frontend",
```

2021-12-08 06:27 UTC, justuswilhelm commented
When running npm install, I receive the following warning
```
27 vulnerabilities (16 moderate, 9 high, 2 critical)

To address all issues (including breaking changes), run:
  npm audit fix --force
```

2021-12-08 06:29 UTC, justuswilhelm commented
When running `npm start` and opening the page in the browser, I receive the following error:
> Failed to compile
```
./src/components/Welcome.tsx
Module not found: Can't resolve '@material-ui/core/Container' in '/Users/justusperlwitz/projectify-frontend/src/components'
```
>This error occurred during the build time and cannot be dismissed.

2021-12-10 11:40 UTC, justuswilhelm commented
I'm still confronted with the following warnings

```
npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated rollup-plugin-babel@4.4.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-babel.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

added 2120 packages, and audited 2121 packages in 49s

154 packages are looking for funding
  run `npm fund` for details

27 vulnerabilities (16 moderate, 9 high, 2 critical)

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```

and when running npm build I get

```
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.5.0

YOUR TYPESCRIPT VERSION: 4.5.2

Please only submit bug reports when using the officially supported version.
```

I think the problem is with running create-react-app. This comment [here](https://github.com/facebook/create-react-app/issues/11174#issuecomment-986701519) hints to switching to webpack being the solution. Could you evaluate switching to webpack to resolve this?

2021-12-10 11:41 UTC, justuswilhelm commented
According to the article I previously linked, switching to next.js might be a good option: https://nextjs.org/docs/migrating/from-create-react-app

2021-12-10 12:43 UTC, Mygithub-me commented
> I'm still confronted with the following warnings
> 
> ```
> npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
> npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
> npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
> npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
> npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
> npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
> npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
> npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
> npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
> npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
> npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
> npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
> npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
> npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
> npm WARN deprecated rollup-plugin-babel@4.4.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-babel.
> npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
> npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
> npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
> npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
> npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
> 
> added 2120 packages, and audited 2121 packages in 49s
> 
> 154 packages are looking for funding
>   run `npm fund` for details
> 
> 27 vulnerabilities (16 moderate, 9 high, 2 critical)
> 
> To address all issues (including breaking changes), run:
>   npm audit fix --force
> 
> Run `npm audit` for details.
> ```
> 
> and when running npm build I get
> 
> ```
> WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.
> 
> You may find that it works just fine, or you may not.
> 
> SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.5.0
> 
> YOUR TYPESCRIPT VERSION: 4.5.2
> 
> Please only submit bug reports when using the officially supported version.
> ```
> 
> I think the problem is with running create-react-app. This comment [here](https://github.com/facebook/create-react-app/issues/11174#issuecomment-986701519) hints to switching to webpack being the solution. Could you evaluate switching to webpack to resolve this?

2021-12-10 12:50 UTC, Mygithub-me commented
> I'm still confronted with the following warnings
> 
> ```
> npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
> npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
> npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
> npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
> npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
> npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
> npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
> npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
> npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
> npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
> npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
> npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
> npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
> npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
> npm WARN deprecated rollup-plugin-babel@4.4.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-babel.
> npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
> npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
> npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
> npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
> npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
> 
> added 2120 packages, and audited 2121 packages in 49s
> 
> 154 packages are looking for funding
>   run `npm fund` for details
> 
> 27 vulnerabilities (16 moderate, 9 high, 2 critical)
> 
> To address all issues (including breaking changes), run:
>   npm audit fix --force
> 
> Run `npm audit` for details.
> ```
This I m facing issues in resolving in 'npm audit'

2021-12-10 12:52 UTC, Mygithub-me commented
> and when running npm build I get
> 
> ```
> WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.
> 
> You may find that it works just fine, or you may not.
> 
> SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.5.0
> 
> YOUR TYPESCRIPT VERSION: 4.5.2
> 
> Please only submit bug reports when using the officially supported version.
> ```
> 
> I think the problem is with running create-react-app. This comment [here](https://github.com/facebook/create-react-app/issues/11174#issuecomment-986701519) hints to switching to webpack being the solution. Could you evaluate switching to webpack to resolve this?

STILL WORKING ON THIS

2021-12-13 04:02 UTC, justuswilhelm commented on src/components/Welcome.tsx
> +                <p>A welcome page is usually one or more web pages or modal overlays that appear the first time you open an app. The best welcome pages direct a user’s focus to the welcome message, w
Can you change this text to lorem ipsum?

2021-12-14 02:43 UTC, justuswilhelm submitted a review, later dismissed

2021-12-14 02:50 UTC, merged